[package]
name = "bastion-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", rev = "54508e9" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", rev = "54508e9" }

[[bin]]
name = "bastion-ebpf"
path = "src/main.rs"